import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Layout from "../components/Layout";
import AboutSection from "../components/sections/AboutSection";
import HomeSection from "../components/sections/HomeSection";
import JourneySection from "../components/sections/JourneySection";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeSection />
      <JourneySection />
      <AboutSection />
      <Script
        strategy="beforeInteractive"
        src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js"
      />
      <Script
        strategy="beforeInteractive"
        src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/ScrollTrigger.min.js"
      />
      <Script defer src="/js/animate.js" />
    </Layout>
  );
}
